/**
  * aside module.
  * @module js/utilities.js
  */

/** Class representing a tree node */
class TreeNode {
  /**
    * Create a node object with element and children.
    * @property {HTMLElement} element: DOM Element represented by current
    * object.
    * @property {Array} children: Array of Child TreeNodes of the object.
    */
  constructor (element) {
    this.element = element;
    this.children = [];
  }
}

/**
  * Return a childrens array according to provided objects array.
  * @param {Array} ...arr Spreaded arguments array
  * @returns {Array} Array of children where each element is typeof TreeNode
  */
function childArray (...arr) {
  // Define chidren array to hold all children objects
  const children = [];
  /**
    * For each object in ...arr, construct TreeNode object with their element
    * attributes given a class list and inner text and when finished appended
    * to children array.
    */
  for (let i = 0; i < arr.length; i++) {
    const obj = new TreeNode(elementMaker(arr[i].elem));
    if (arr[i].classList) obj.element.classList.add(...arr[i].classList);
    if (arr[i].content) obj.element.innerText = arr[i].content;
    if (arr[i].attribs) {
      for (const prop in arr[i].attribs) {
        obj.element.setAttribute(prop, arr[i].attribs[prop]);
      }
    }
    children.push(obj);
  }
  // Return children array
  return children;
}

function elementMaker (elem) {
  return document.createElement(elem);
}

/**
  * Recursively construct DOM Tree of provided parameter. Provided parameter
  * is a tree structure containing root element and childrens array for each
  * node.
  * @param {TreeNode} root A tree structure generated by makeProjectCard
  * @returns {HTMLElement} Fully constructed HTML parent Element.
  */
function makeNodeTree (root) {
  /**
    * If card parameter has children, then for each child recursively append
    * its children and when done return that child. All levels of card tree
    * will be traversed.
    */
  if (root.children.length !== 0) {
    for (let i = 0; i < root.children.length; i++) {
      root.element.append(makeNodeTree(root.children[i]).element);
    }
  }
  return root;
}

export { elementMaker, TreeNode, childArray, makeNodeTree };
